import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Provider } from "@/components/Provider/Provider";
import { Toaster } from "@/components/shared/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="h-full">
            <body className={inter.className}>
                <Provider>
                    <div className="flex min-h-full flex-col items-center justify-center p-32 max-w-7xl">
                        {children}
                    </div>
                </Provider>
                <Toaster />
            </body>
        </html>
    );
}
